name: C++ Insighs Builder Docker Image CI

on:
  push:
    branches: [master]

  repository_dispatch:
    types: [rebuild_trigger]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build the Docker image
        run: |
            make build
            docker images

      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u andreasfertig --password-stdin

      - name: Push the tagged Docker image
        run: |
            docker tag andreasfertig/cppinsights-builder andreasfertig/cppinsights-builder
            docker push andreasfertig/cppinsights-builder

      - name: Notify listeners
        run: |
            sleep 5
            curl -X POST -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ secrets.GH_TRIGGER }}" https://api.github.com/repos/andreasfertig/cppinsights-builder-gitpod/dispatches -d '{"event_type":"rebuild_trigger"}' &> /dev/null
